#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pdf:
  path: '/generate-pdf'
  controller: App\Controller\PdfController::generatePdf

app_plannification_index:
  path: /plannification
  methods: [GET, POST]
  controller: App\Controller\PlannificationController::index

app_plannification_generate_qr_code:
  path: '/plannification/generate-qr-code'
  controller: App\Controller\PlannificationController::generateQrCodeAction



